# Modified by Kaige Gao in 2026 for a cost-controlled GitHub Action fork.
name: 'The PR Agent'
description: 'Summarize, review and suggest improvements for pull requests'
branding:
  icon: 'award'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile.github_action'
